# Generated by Django 4.0.6 on 2022-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students_course_subject_course_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
