# Generated by Django 4.0.6 on 2022-07-30 15:09

from django.db import migrations, models
import utils.helping_functions


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentsubmission_grade_alter_assignment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(null=True, upload_to=utils.helping_functions.get_assignment_submission_path),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='assignment_student_unique'),
        ),
    ]
